// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrgmphxnizephwqyduak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyZ21waHhuaXplcGh3cXlkdWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzE0MTEsImV4cCI6MjA3MTU0NzQxMX0.LT35j7Rg-nVrh_BHN9zXzlkFrOhoNJHbfg0G9lvQSis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});